
// export Button from 'react-bootstrap/lib/Button';
// export ButtonGroup from 'react-bootstrap/lib/ButtonGroup';
// export ButtonInput from 'react-bootstrap/lib/';
// export Dropdown from 'react-bootstrap/lib/';
// export DropdownButton from 'react-bootstrap/lib/';
// export FromGroup from 'react-bootstrap/lib/';
// export FromControls from 'react-bootstrap/lib/';
// export Input from 'react-bootstrap/lib/';
// export InputBase from 'react-bootstrap/lib/';
// export Label from 'react-bootstrap/lib/';
// export ListGroup from 'react-bootstrap/lib/';
// // export  from 'react-bootstrap/lib/';
// // export  from 'react-bootstrap/lib/';
// // export  from 'react-bootstrap/lib/';
// // export  from 'react-bootstrap/lib/';
// // export  from 'react-bootstrap/lib/';
// // export  from 'react-bootstrap/lib/';
// // export  from 'react-bootstrap/lib/';
// // export  from 'react-bootstrap/lib/';
// // export  from 'react-bootstrap/lib/';
// // export  from 'react-bootstrap/lib/';
// // export  from 'react-bootstrap/lib/';
// // export  from 'react-bootstrap/lib/';
// // export  from 'react-bootstrap/lib/';
const context = require.context('.', false, /\.js(x)?$/);
const coms = {};
context.keys().forEach((key) => {
  const k = key.replace(/^\.\/(.*)\.js(x)?$/, '$1');
  coms[k] = context(key).default;
});
module.exports = coms;
